exports.Msg = {
    verificationSuccess: 'Verification sent successfully.',
    otpMessage: 'This is your OTP: 1234. You can now log in.',
    otpVerified: 'Your OTP has been verified successfully.',
    serverError: 'Internal server error. Please try again later.',
    unauthorizedAccess: 'You are not authorized to access this resource.',
    tokenMissing: 'Authorization token is missing.',
    tokenExpired: 'Your session has expired. Please log in again.',
    invalidToken: 'The provided token is invalid.',
    tokenRequired: 'Authorization token is required',
    profileUpdatedSuccessfully: 'Profile updated successfully',
    profileUpdatedFailed: 'Profile not updated',
    dataFoundSuccess: "Data found successfully.",
    dataFoundFailed: "Data not found. Please try again.",
    productAddFailed: 'Failed to add product',
    productAddSuccess: 'Product added successfully',
    productNotFound: "No products found. Please add products to view them here.",
    productFoundSuccess: "Products retrieved successfully.",
    productAlreadyRent: "This product is already rented, so editing and delete is not allowed until it becomes available.",
    productUpdateSuccess: "Product updated successfully.",
    productUpdateFailed: "No product was updated. Please check the product ID or the provided data.",
    productDeleteSuccess: "products deleted successfully.",
    noSubcategoryFoundForGivenCategoryId: "No subcategory found for the given category.",
    subCategoryFoundSuccess: "Subcategories retrieved successfully.",
    noSubcategoryFound: "No subcategories found.",
    chatDeletedSuccessfull: "Chat deleted successfully",
    chatNotDeleted: "Chat could not be deleted",
    idRequired: "Id must be require",
    reportsSendSuccessfully: "The message report has been successfully sent to the admin.",
    reportsNotSend: "The message report could not be sent to the admin.",
    userLocationNotFound: "User location not found",
    featuresNotFound: "Features not found",
    featuresFoundSuccessfull: "Features founded successfully",
    notificationFoundSuccessfull: "Notification found successfull",
    notificationNotFound: "Notification not found",
    noChatFound: "No chats found to delete.",
    chatDeletedSuccessfully: "All chats cleared successfully.",
    accountDeletedSuccessfully: "Account deleted successfully.",
    accountNotDeleted: "Account deletion failed. Please try again later.",
    chatDeletedById: "chats cleared successfully.",
    userBlockedSuccessfully: "User has been successfully blocked.",
    userUnBlockedSuccessfully: "User has been successfully unblocked.",
    searchSuggestionsNotFound: "Search suggestions not found",
    searchSuggestionsFoundSuccessfull: "Search suggestions founded successfully",

    loginSuccess: "Login successful.",
    userRegisterSuccess: "User registered successfully.",
    authFailed: "Authentication failed. Please check your credentials and try again.",
    userCreationFailed: "User creation failed. Please try again later.",
    productFoundSuccess: "Products fetched successfully.",
    noBlockedUsersFound: "No blocked users found.",
    blockedUsersFetchedSuccesfully: "Blocked users fetched successfully.",
    reviewAlreadySubmitted: 'You have already submitted a review and rating for this product.',
    reviewSubmittedSuccess: 'Your review and rating have been submitted successfully.',
    reviewSubmitFailed: 'Unable to submit your review and rating. Please try again later.',


    // ===== Gigs =====
    gigsAddSuccess: "Gig added successfully.",
    gigsAddFailed: "Failed to add gig.",
    gigsDeleteSuccess: "Gig deleted successfully.",
    gigsNotFound: "Gig not found.",

    // ===== Comments =====
    commentAddSuccess: "Comment added successfully.",
    commentAddFailed: "Failed to add comment.",
    commentDeleteSuccess: "Comment deleted successfully.",
    commentNotFound: "Comment not found.",

    // ===== Likes =====
    likeSuccess: "Post liked successfully.",
    likeFailed: "Failed to like post.",
    unlikeSuccess: "Post unliked successfully.",
    unlikeFailed: "Failed to unlike post.",
    likeAlreadyExists: "You have already liked this post.",
    likeNotFound: "Like not found.",

    // ===== Favorites =====
    favoriteAddSuccess: "Post added to favorites.",
    favoriteAddFailed: "Failed to add to favorites.",
    unfavoriteSuccess: "Post removed from favorites.",
    unfavoriteFailed: "Failed to remove from favorites.",
    favoriteAlreadyExists: "This post is already in your favorites.",
    favoriteNotFound: "Favorite not found.",
    favoriteRemove: "Post removed from favorites.",

    userHaveNoPosts: "This user has no favorite posts.",
    userHaveNoChats: "No chats found for this user",
    chatListFounded: "User chat list fetched successfully",

};
